apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: express-prod-east
  labels:
    app: express
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: csdp-salesdemo-prod-east # temporarily set to Runtime namespace, CR-10565
    name: in-cluster
  project: express
  source:
    path: ./kustomize/express/overlays/prod-east
    repoURL: https://github.com/codefresh-contrib/csdp-salesdemo_applications.git
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    # automated:
    #   prune: true