apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: color
configMapGenerator:
- literals:
  - COLOR1=orange
  name: color-config
  namespace: color
images:
- name: color-service
  newName: salesdemosa/example-multiservice2
  newTag: 0edfe88
