apiVersion: v2
name: stage
description: A Helm chart for Kubernetes
type: application
version: 0.1.12
dependencies:
  - name: buslog
    version: "1.4.2"
    repository: "https://h.cfcr.io/codefreshdemo/public"
  - name: ctrlr
    version: "7.7.7"
    repository: "https://h.cfcr.io/codefreshdemo/public"
  - name: flask-ui
    version: "5.5.5"
    repository: "https://h.cfcr.io/codefreshdemo/public"
