apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: color
configMapGenerator:
- literals:
  - COLOR1=yellow
  name: color-config
  namespace: color
images:
- name: color-service
  newName: docker.io/salesdemosa/example-multiservice2
  newTag: 5ee1abc
