apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: color
configMapGenerator:
- literals:
  - COLOR1=yellow
  name: color-config
  namespace: color
images:
- name: quay.io/codefresh_sa/color-service
  newName: salesdemosa/color
  newTag: 971b6d3
